spring:
  profiles:
    active: test

---

spring:
  profiles: test
  datasource:
    data: classpath:data.sql
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      jdbc-url: jdbc:h2:file:~/fcm-test;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true


server:
  port: 8888
