spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:file://~/fcm;
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

server:
  port: 8888
